### ISSUE TITLE
Reading together: 《Steal Like an Artist》

### ISSUE THREAD

**Issue by Demian101** [CreatorsDAO/web3-English-co-learn#3]
- https://book.douban.com/subject/7061613/
- https://www.goodreads.com/search?utf8=%E2%9C%93&q=read+this+for+inspiration&search_type=books

<img width="948" alt="image" src="https://github.com/CreatorsDAO/web3-English-co-learn/assets/33189338/de500eb7-19b1-4e73-9e85-28471f681434">

The book is only 160 pages

feel free to read it with me together.

**Comment by Demian101** [comment]
1. 约定本周3 次 online 视频一起 share & 口语分享。
2. 约定周末一次总结对话，主要谈论本书的内容总结 和 对你的启发

分享完之后，使用 https://github.com/orgs/CreatorsDAO/discussions/48 工具 improve

----

拖延惩罚 punishment ：

**Show me your bookshelf, and give me a book.**

具体做法：两个人约定好要做的事情，并约定未完成惩罚：比如我推荐一个很有趣味的惩罚措施：
- A、B 约定好本周共同阅读第一章，并且互相口语分享。
- 但是 A 爽约没来参会
- A 需要向 B 展示他的书架，B 挑选一本他喜欢的书，A 将这本书邮寄给 B。

**Comment by Demian101** [comment]
## Goal for this week: 

### finish reading the **first 5 chapters**

#### We will discuss it next Saturday, probably **12.02 20:00 (utc+8)**

<img width="1024" alt="image" src="https://github.com/CreatorsDAO/web3-English-co-learn/assets/33189338/5ca03521-fc27-401e-bf04-434851b11faf">

**Comment by mengdiliao** [comment]
Cool :D

**Comment by yanboishere** [comment]
cheer！
